### ISSUE TITLE
C2 certificates created without consultant email, shows as "no state"

### ISSUE THREAD

**Issue by jynxiesue** [knieper/crltmich#23]
I tried to test to see how a C2 created through requesting a Midterm Student Feedback but because I'm not a graduate student, it did not show up in my portfolio.  Here is a screen shot of the page after hitting submit (Please note that there is a failed to load the specified GTC account in the yellow bar in the screenshot below.):
![screen shot 2016-02-11 at 9 53 21 am](https://cloud.githubusercontent.com/assets/16547623/12979496/9bfed546-d0a5-11e5-9347-42f82e8bbb10.png)

**Comment by jynxiesue** [comment]
Please note that there is a failed to load the specified GTC account.

**Comment by jynxiesue** [comment]
Screen shot of the email I received with "
![screen shot 2016-02-11 at 10 02 06 am](https://cloud.githubusercontent.com/assets/16547623/12979657/93712bf8-d0a6-11e5-86c1-c01f1ef15ac5.png)
Dear name"

**Comment by jynxiesue** [comment]
Screen shot with the email I received with "Dear name".
![screen shot 2016-02-11 at 10 02 06 am](https://cloud.githubusercontent.com/assets/16547623/12979673/b15c79f6-d0a6-11e5-89fa-10a87cc016bb.png)

**Comment by mbakewel** [comment]
In looking at the webform (http://crlt.umich.edu/node/3/webform) the default value for the First and Last Name field is blank, but the default value "name" shows up on the form anyway. I tried changing it to something else - "Meg Bakewell" - and it still shows up as "name" on the form. I don't know  why it's doing this!

**Comment by knieper** [comment]
In testing by changing the form key value from 'name' to 'names' I was able to get the profile token to come through. I suspect that there is a name clash because search the mysql table for webform components shows 19 different webform components with the key of 'name'. 

*If the user does not have their profile name filled in then it leaves the field blank. It is required so the user must fill it in. 

This should be correct on production already since it was just a minor configuration change via the browser - no code changes required - and tests as a graduate student show the webform to node process and the certification creation process with workflow of 'approved' is working fine.
