### ISSUE TITLE
inconsistencies in B certificate labeling

### ISSUE THREAD

**Issue by anjirlly** [knieper/crltmich#25]
Seminars/workshops that we describe as B2 eligible in event nodes generate B1 certificates (including B1_it and B1_mc), leading to confusion among participants and staff. Additionally, May PFF Seminar event nodes (e.g., 58977) marked B3 have been generating B2 certificates.

The parts that need to be consistent:

1) official requirements http://www.crlt.umich.edu/sites/default/files/certificaterequirements_20140401.pdf 

2) learning about teaching requirements webpage
http://www.crlt.umich.edu/um.gtc/focal_area_b_resources_and_support
(Meg changed this to match 1.)

3) "eligible for certificate" field options in event node

4) going forward, B2 certificates being produced from B2 events and B3 certificates from B3 events

45 looking backward, a massive reclassification of certificate labels? This needs to be thought through very carefully and approved by Meg.
May PFF B2 certificates should become B3 certificates
Old, non-CRLT, course-based B2 certificates should become B1 certificates
CRLT workshops/seminars that were labeled B1(including _it and _mc variants) should be labeled B2, with appropriate variants.
Departmental workshops approved until now as B1 certificates should become B2 certificates (or maybe not). Would it help matters to split departmental workshops out to their own B designation? Another source of confusion for participants is what kinds of events appear automagically (CRLT-sponsored orientations and workshops/seminars and May PFF) and what kinds of events they have to submit documentation for. My brain would be happiest if, henceforth, B1 and B2 were fulfilled from non-CRLT sources, while B3 and a new B4 were CRLT-based (May PFF seminar and workshops/seminars, respectively). My hope is that this would be easier than dealing with B2 certificates as a single bin combining CRLT and non-CRLT workshops.
5) instructions to participants on page where they can see their completed requirements. (Can't provide an example that's identity free, but the page has heading about 2/3 of way down that says, "Submit new documentation for the Graduate Teacher Certificate.") B 1 and 2 content needs to be flipped here. Ideally, it would be helpful to participants if they could see somewhere in the vicinity a note about the certificates that are handled via CRLT's database (and that they therefore do NOT need to submit). Meg, I think participants use this "submit new documentation" outline instead of studying the requirements and resources in the program webpage. And so they think they need to submit stuff that they may not need to (departmental GSI orientation or course) and that they only need 1 GSI appointment.

**Comment by mbakewel** [comment]
I prefer not to introduce a new category of b4, but otherwise agree with the above. CRLT and non_CRLT B2s should all stay B2s, and we should clarify language/instructions (CRLT can do this) about when participants need to submit info, and when it is automatically added to their portfolio. 

To clarify (5), there are links on pages /usre/uid/certificates that allow participants to submit certificate documentation. the labeling there under B1, B2, needs to be made consistnent with the B1, b2, b3 as described in the offical requirements: http://www.crlt.umich.edu/sites/default/files/certificaterequirements_20140401.pdf

**Comment by knieper** [comment]
I think I've been able to figure out how to switch the b1/b2 labels so that the website nodes match the schema on the print out; however, b3s do not exist as a separate entity on the website. Currently, events coded as eligible for b3 create b2s. Should a new type of certificate called b3 be created?

**Comment by anjirlly** [comment]
Meg, regarding the B3 question, do you agree that we need a B3 certificate?
The instructions will need to say that it only needs to be be submitted by
people completing the Engaged Pedagogy Initiative. CRLT already collects
attendance data for the first 2 options (May PFF Seminar, and Training for
Diversity and Inclusive Teaching).

For node 89220 (2016 May PFF Seminar), those attendees are marked as
eligible for a B3.

Meg, can I please have a live file of the pdf you sent Sharon to update?

**Comment by knieper** [comment]
Per phone call 8-4-16 we will eventually create a B3 on the website, but that since it is a new piece it will wait until another project based funding or until an hourly/per issue plan is set up.

Ensuring that B1s and B2s on the website align with the paper description will be worked on for the next check in at the end of August.

**Comment by knieper** [comment]
B1s and B2s should be created on the staging copy of website as described on the printable document. - Ready for testing.

**Comment by knieper** [comment]
pushed to production
