### ISSUE TITLE
Users report that they cannot see their "sign ups" when they go into their account.

### ISSUE THREAD

**Issue by jynxiesue** [knieper/crltmich#5]

**Comment by knieper** [comment]
Fixed with a new version of the signups view ('signups current') to be a 'signup' view type instead of a 'node' view type. 

Fields displayed are based on the previous view which was an overridden version of a signup module default view ('signup_current_signups'): shows the node title, the user's registration status and attendance in a table format. 

Node code changes were required - just a change in the database configuration via the views module.
